### ISSUE TITLE
Cannot set fish as default shell for alacritty

### ISSUE THREAD

**Issue by dat-le-4** [benbrastmckie/.config#90]
I tried to config the Alacritty.yml file like this but when reset tmux the default shell still zsh.
<img width="651" alt="Screenshot 2023-02-04 at 13 39 50" src="https://user-images.githubusercontent.com/96510793/216784066-dcae6a56-a08c-4020-9764-eeab7b068bba.png">

**Comment by benbrastmckie** [comment]
Are you sure you got that path right? You can check by running `which fish` in the terminal. My alacritty.yml file includes:
```
shell:
  program: /usr/bin/fish
  args:
    - -l
    - -c
    - "tmux"
```
